project_name: afx
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: afx
    ldflags:
      - -s -w
      - -X github.com/babarot/afx/cmd.Version={{ .Version }}
      - -X github.com/babarot/afx/cmd.BuildTag={{ .Tag }}
      - -X github.com/babarot/afx/cmd.BuildSHA={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
